# Generated by Django 5.2 on 2025-04-26 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tasa_rendimiento', models.DecimalField(decimal_places=2, help_text='Tasa anual', max_digits=5)),
                ('plazo_minimo', models.IntegerField(help_text='Plazo mínimo en meses')),
                ('plazo_maximo', models.IntegerField(help_text='Plazo máximo en meses')),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Inversión',
                'verbose_name_plural': 'Tipos de Inversión',
            },
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo', models.IntegerField(help_text='Plazo en meses')),
                ('tasa_rendimiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_simulacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_inversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inversiones.tipoinversion')),
            ],
            options={
                'verbose_name': 'Inversión',
                'verbose_name_plural': 'Inversiones',
            },
        ),
        migrations.CreateModel(
            name='PlazoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazo_meses', models.IntegerField()),
                ('tasa_rendimiento', models.DecimalField(decimal_places=2, help_text='Tasa específica para este plazo', max_digits=5)),
                ('tipo_inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plazos', to='inversiones.tipoinversion')),
            ],
            options={
                'verbose_name': 'Plazo de Inversión',
                'verbose_name_plural': 'Plazos de Inversión',
                'unique_together': {('tipo_inversion', 'plazo_meses')},
            },
        ),
    ]
