# Generated by Django 5.2 on 2025-04-29 23:17

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plazoinversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='plazoinversion',
            name='tipo_inversion',
        ),
        migrations.RenameField(
            model_name='tipoinversion',
            old_name='activo',
            new_name='es_activo',
        ),
        migrations.RemoveField(
            model_name='tipoinversion',
            name='tasa_rendimiento',
        ),
        migrations.AddField(
            model_name='tipoinversion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoinversion',
            name='monto_maximo',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoinversion',
            name='rentabilidad_anual_maxima',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoinversion',
            name='rentabilidad_anual_minima',
            field=models.DecimalField(decimal_places=2, default=0.06, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoinversion',
            name='riesgo',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='MEDIO', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoinversion',
            name='descripcion',
            field=models.TextField(default='Inversion'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PerfilRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('nivel_riesgo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tipos_inversion_recomendados', models.ManyToManyField(related_name='perfiles_riesgo', to='inversiones.tipoinversion')),
            ],
            options={
                'verbose_name': 'Perfil de riesgo',
                'verbose_name_plural': 'Perfiles de riesgo',
            },
        ),
        migrations.DeleteModel(
            name='Inversion',
        ),
        migrations.DeleteModel(
            name='PlazoInversion',
        ),
    ]
