# Generated by Django 5.2 on 2025-05-07 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0002_alter_plazoinversion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_invertido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo', models.IntegerField()),
                ('reinversion_intereses', models.BooleanField(default=False)),
                ('interes_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rentabilidad_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_inversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inversiones.tipoinversion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones_inversion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
