# Generated by Django 5.2 on 2025-04-26 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('fijo', 'Valor Fijo'), ('porcentaje', 'Porcentaje del Monto')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo Adicional',
                'verbose_name_plural': 'Cargos Adicionales',
            },
        ),
        migrations.CreateModel(
            name='TipoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tasa_interes', models.DecimalField(decimal_places=2, help_text='Tasa anual', max_digits=5)),
                ('plazo_maximo', models.IntegerField(help_text='Plazo máximo en meses')),
                ('monto_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Crédito',
                'verbose_name_plural': 'Tipos de Crédito',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo', models.IntegerField(help_text='Plazo en meses')),
                ('tasa_interes', models.DecimalField(decimal_places=2, help_text='Tasa anual', max_digits=5)),
                ('sistema_amortizacion', models.CharField(choices=[('frances', 'Sistema Francés (Cuota Fija)'), ('aleman', 'Sistema Alemán (Capital Fijo)')], max_length=20)),
                ('fecha_simulacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
            },
        ),
        migrations.CreateModel(
            name='CreditoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creditos.cargoadicional')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditos.credito')),
            ],
            options={
                'verbose_name': 'Cargo por Crédito',
                'verbose_name_plural': 'Cargos por Crédito',
            },
        ),
        migrations.AddField(
            model_name='credito',
            name='cargos_adicionales',
            field=models.ManyToManyField(through='creditos.CreditoCargo', to='creditos.cargoadicional'),
        ),
        migrations.AddField(
            model_name='credito',
            name='tipo_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creditos.tipocredito'),
        ),
    ]
