# Generated by Django 5.2 on 2025-04-28 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditocargo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='cargos_adicionales',
        ),
        migrations.RemoveField(
            model_name='creditocargo',
            name='credito',
        ),
        migrations.AlterModelOptions(
            name='credito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipocredito',
            options={},
        ),
        migrations.RenameField(
            model_name='credito',
            old_name='fecha_simulacion',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='sistema_amortizacion',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='tasa_interes',
        ),
        migrations.RemoveField(
            model_name='tipocredito',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tipocredito',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tipocredito',
            name='tasa_interes',
        ),
        migrations.AddField(
            model_name='credito',
            name='metodo_pago',
            field=models.CharField(default='Efectivo', max_length=10),
        ),
        migrations.AddField(
            model_name='credito',
            name='monto_prestamo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credito',
            name='monto_vivienda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocredito',
            name='plazo_minimo',
            field=models.IntegerField(default=12, help_text='Plazo mínimo en meses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocredito',
            name='tasa_interes_referencial',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credito',
            name='tipo_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditos.tipocredito'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipocredito',
            name='monto_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tipocredito',
            name='monto_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='CargoAdicional',
        ),
        migrations.DeleteModel(
            name='CreditoCargo',
        ),
    ]
