# Generated by Django 5.2 on 2025-05-03 22:37

from django.db import migrations, models

# Inicialización de datos según la propuesta de seguros
def actualizar_tasas_seguro(apps, schema_editor):
    TipoCredito = apps.get_model('creditos', 'TipoCredito')

    # Mapeo de tipos de crédito con sus tasas de seguro correspondientes
    mapeo_seguros = {
        'Vivienda de interés social': {'desgravamen': 0.03, 'bien': 0.05},
        'Línea abierta': {'desgravamen': 0.04, 'bien': 0.00},
        'Hipotecario vivienda': {'desgravamen': 0.03, 'bien': 0.05},
        'Vivienda de interés público': {'desgravamen': 0.03, 'bien': 0.05},
        'Educación superior': {'desgravamen': 0.04, 'bien': 0.00},
        'Vehicular': {'desgravamen': 0.04, 'bien': 0.08},
    }

    # Actualizar cada tipo de crédito con sus tasas de seguro
    for tipo in TipoCredito.objects.all():
        if tipo.nombre in mapeo_seguros:
            tipo.tasa_seguro_desgravamen = mapeo_seguros[tipo.nombre]['desgravamen']
            tipo.tasa_seguro_bien = mapeo_seguros[tipo.nombre]['bien']
            tipo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_remove_creditocargo_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocredito',
            name='tasa_interes_maxima',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tipocredito',
            name='tasa_interes_minima',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tipocredito',
            name='tasa_seguro_bien',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Tasa mensual de seguro del bien (porcentaje)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tipocredito',
            name='tasa_seguro_desgravamen',
            field=models.DecimalField(decimal_places=3, default=0.03, help_text='Tasa mensual de seguro de desgravamen (porcentaje)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='credito',
            name='metodo_pago',
            field=models.CharField(choices=[('frances', 'Método Francés'), ('aleman', 'Método Alemán')], default='frances', max_length=10),
        ),
        migrations.RunPython(actualizar_tasas_seguro),
    ]
