# Generated by Django 5.2 on 2025-05-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_agregar_tasas_seguros'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocredito',
            name='seguros',
            field=models.JSONField(default=dict, help_text='Tasas de seguros en formato JSON'),
        ),
    ]
