# Generated by Django 5.2 on 2025-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionglobal',
            name='nombre',
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='descripcion_corta',
            field=models.CharField(default='Somos una institución financiera comprometida con tu desarrollo económico y bienestar financiero.', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='direccion',
            field=models.CharField(default='Av. Principal 123, Ciudad', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='email_contacto',
            field=models.EmailField(default='contacto@ahorrofuturo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='email_soporte',
            field=models.EmailField(default='soporte@ahorrofuturo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='horario_atencion',
            field=models.CharField(default='Lun-Vie: 9:00 - 17:00', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='horario_emergencias',
            field=models.CharField(default='24/7 para emergencias', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='nombre_sitio',
            field=models.CharField(default='Ahorro Futuro', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='telefono_atencion',
            field=models.CharField(default='800 123 4567', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='telefono_principal',
            field=models.CharField(default='(01) 123-4567', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='texto_copyright',
            field=models.CharField(default='Todos los derechos reservados.', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='texto_legal',
            field=models.CharField(default='Supervisado por la Superintendencia de Banca y Seguros.', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracionglobal',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
